import { TimelineEvent, EventType } from './types';

export const INITIAL_EVENTS: TimelineEvent[] = [
  {
    id: 'neolithic-yangshao',
    title: 'Yangshao Culture: Painted Pottery',
    titleZh: '新石器时代：仰韶彩陶',
    year: 'c. 5000–3000 BC',
    yearZh: '约公元前 5000–3000 年',
    sortYear: -5000,
    description: 'Before true porcelain, the Yangshao culture along the Yellow River created distinct red earthenware. This basin features a fish design, painted in black slip on a reddish body. It represents the "Painted Pottery" phase.',
    descriptionZh: '在真正的瓷器诞生之前，黄河流域的仰韶文化创造了独特的红陶。这个陶盆绘有人面鱼纹，是在红色陶体上用黑色泥浆绘制的。',
    type: EventType.HISTORICAL,
    tags: ['Neolithic', 'Earthenware', 'Painted Pottery', 'Yangshao'],
    tagsZh: ['新石器时代', '陶器', '彩陶', '仰韶文化'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Painted_pottery_basin_with_human_face_and_fish_designs.jpg/1280px-Painted_pottery_basin_with_human_face_and_fish_designs.jpg'
  },
  {
    id: 'shang-proto',
    title: 'Shang Dynasty: Proto-Porcelain',
    titleZh: '商代：原始瓷尊',
    year: 'c. 1600–1046 BC',
    yearZh: '约公元前 1600–1046 年',
    sortYear: -1600,
    description: 'The Shang dynasty saw the birth of "Proto-porcelain" (yuanshi ci). Made of kaolin-rich clay and fired at high temperatures with a lime-based glaze.',
    descriptionZh: '商代见证了“原始瓷”（yuanshi ci）的诞生。由富含高岭土的粘土制成，并在高温下使用石灰釉烧制。',
    type: EventType.COURSE,
    tags: ['Shang Dynasty', 'Proto-porcelain', 'Kaolin', 'High-fired'],
    tagsZh: ['商代', '原始瓷', '高岭土', '高温烧制'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Shang_Proto-porcelain_Zun.jpg/800px-Shang_Proto-porcelain_Zun.jpg'
  },
  {
    id: 'han-greenware',
    title: 'Han Dynasty: Greenware Tower',
    titleZh: '东汉：绿釉陶楼',
    year: '206 BC – 220 AD',
    yearZh: '公元前 206 年 – 公元 220 年',
    sortYear: -206,
    description: 'During the Han, green-glazed stoneware became widespread. This architectural model served as "mingqi" (spirit goods) for the afterlife.',
    descriptionZh: '汉代时期，绿釉陶器变得普遍。这座陶楼模型作为“明器”（随葬品），旨在为死者在来世提供住所。',
    type: EventType.HISTORICAL,
    tags: ['Han Dynasty', 'Celadon Origins', 'Mingqi', 'Burial Goods'],
    tagsZh: ['汉代', '青瓷起源', '明器', '随葬品'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Han_glazed_pottery_tower.JPG/800px-Han_glazed_pottery_tower.JPG'
  },
  {
    id: 'tang-sancai',
    title: 'Tang Dynasty: Sancai Camel',
    titleZh: '唐代：三彩载乐驼',
    year: '618–907 AD',
    yearZh: '公元 618–907 年',
    sortYear: 618,
    description: 'The cosmopolitan Tang Dynasty is epitomized by "Sancai" (Three-Color) wares. The low-fired lead glazes create signature amber, green, and cream splashes.',
    descriptionZh: '国际化的唐代以“唐三彩”为代表。低温铅釉形成了标志性的琥珀色、绿色和奶油色斑块。',
    type: EventType.COURSE,
    tags: ['Tang Dynasty', 'Sancai', 'Silk Road', 'Polychrome'],
    tagsZh: ['唐代', '唐三彩', '丝绸之路', '多色釉'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Sancai_camel_musicians_NMB_Bern_1993.200.jpg/1024px-Sancai_camel_musicians_NMB_Bern_1993.200.jpg'
  },
  {
    id: 'tang-xing',
    title: 'Tang Dynasty: Xing White Ware',
    titleZh: '唐代：邢窑白瓷',
    year: 'c. 7th–9th Century',
    yearZh: '约 7–9 世纪',
    sortYear: 700,
    description: 'Celebrated by tea master Lu Yu as "like silver and snow". This high-fired white porcelain set the standard for purity.',
    descriptionZh: '茶圣陆羽赞誉其“类银”、“类雪”。这种高温白瓷确立了纯净的标准。',
    type: EventType.HISTORICAL,
    tags: ['Tang Dynasty', 'White Ware', 'Xing Kiln', 'Tea Culture'],
    tagsZh: ['唐代', '白瓷', '邢窑', '茶文化'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Xing_ware_ewer_Tang_Dynasty.jpg/800px-Xing_ware_ewer_Tang_Dynasty.jpg'
  },
  {
    id: 'song-ru',
    title: 'Northern Song: Ru Ware',
    titleZh: '北宋：汝窑天青釉',
    year: '1086–1125 AD',
    yearZh: '公元 1086–1125 年',
    sortYear: 1086,
    description: 'The pinnacle of Chinese ceramics. Ru ware is famous for its rare "sky-blue after rain" glaze and subtle crazing.',
    descriptionZh: '中国陶瓷的巅峰。汝窑以其罕见的“雨过天青”釉色和微妙的开片而闻名。',
    type: EventType.COURSE,
    tags: ['Northern Song', 'Ru Ware', 'Imperial', 'Monochrome'],
    tagsZh: ['北宋', '汝窑', '宫廷御用', '单色釉'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ru_ware_brush_washer_Palace_Museum.jpg/1024px-Ru_ware_brush_washer_Palace_Museum.jpg'
  },
  {
    id: 'song-ding',
    title: 'Song Dynasty: Ding Ware',
    titleZh: '北宋：定窑白釉',
    year: '960–1279 AD',
    yearZh: '公元 960–1279 年',
    sortYear: 1100,
    description: 'Ding ware is known for its warm, ivory tone and "teardrop" glaze runs, often featuring incised floral decorations.',
    descriptionZh: '定窑以温暖的象牙色调和“泪痕”状釉流而闻名，通常饰有刻花花卉纹样。',
    type: EventType.COURSE,
    tags: ['Song Dynasty', 'Ding Ware', 'White Porcelain', 'Incised'],
    tagsZh: ['宋代', '定窑', '白瓷', '刻花'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Ding_ware_dish_with_daylily.jpg/800px-Ding_ware_dish_with_daylily.jpg'
  },
  {
    id: 'song-jun',
    title: 'Song Dynasty: Jun Ware',
    titleZh: '宋代：钧窑玫瑰紫釉',
    year: 'c. 1100–1300 AD',
    yearZh: '约公元 1100–1300 年',
    sortYear: 1150,
    description: 'Jun ware is famed for its thick, opalescent blue glaze, often splashed with copper oxide to create striking purple or red patches.',
    descriptionZh: '钧窑以其厚重、乳光质感的蓝色釉而闻名，常泼洒氧化铜以形成醒目的紫色或红色斑块。',
    type: EventType.HISTORICAL,
    tags: ['Song Dynasty', 'Jun Ware', 'Purple Splashes', 'Opalescent'],
    tagsZh: ['宋代', '钧窑', '紫斑', '乳光'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Official_Jun_ware_rose-purple_glazed_flowerpot_stand_with_inscription_of_Studio_of_Utilizing_Time%2C_Yuan_or_early_Ming_dynasty%2C_Jun_kilns%2C_stoneware_-_The_David_Collection_-_Copenhagen_-_DSC04868.JPG/800px-Official_Jun_ware_rose-purple_glazed_flowerpot_stand_with_inscription_of_Studio_of_Utilizing_Time%2C_Yuan_or_early_Ming_dynasty%2C_Jun_kilns%2C_stoneware_-_The_David_Collection_-_Copenhagen_-_DSC04868.JPG'
  },
  {
    id: 'song-longquan',
    title: 'Southern Song: Longquan',
    titleZh: '南宋：龙泉窑青瓷',
    year: '1127–1279 AD',
    yearZh: '公元 1127–1279 年',
    sortYear: 1200,
    description: 'Longquan kilns produced massive amounts of greenware with a thick, unctuous plum-green glaze that mimics jade.',
    descriptionZh: '龙泉窑生产了大量青瓷，具有厚重、温润、模仿玉石的梅子青釉。',
    type: EventType.HISTORICAL,
    tags: ['Southern Song', 'Celadon', 'Longquan', 'Jade-like'],
    tagsZh: ['南宋', '青瓷', '龙泉窑', '类玉'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Longquan_celadon_vase_Song_MET.jpg/800px-Longquan_celadon_vase_Song_MET.jpg'
  },
  {
    id: 'yuan-blue-white',
    title: 'Yuan Dynasty: The David Vases',
    titleZh: '元代：大维德青花瓶',
    year: '1351 AD',
    yearZh: '公元 1351 年',
    sortYear: 1351,
    description: 'The most famous blue-and-white porcelain in the world. They prove Jingdezhen mastered imported Persian cobalt by 1351.',
    descriptionZh: '世界上最著名的青花瓷。它们证明景德镇在1351年已掌握了进口波斯钴料的使用。',
    type: EventType.COURSE,
    tags: ['Yuan Dynasty', 'Blue and White', 'Cobalt', 'David Vases'],
    tagsZh: ['元代', '青花瓷', '钴料', '大维德瓶'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/The_David_Vases%2C_British_Museum.jpg/800px-The_David_Vases%2C_British_Museum.jpg'
  },
  {
    id: 'ming-chenghua',
    title: 'Ming Dynasty: Chicken Cup',
    titleZh: '明成化：斗彩鸡缸杯',
    year: '1464–1487 AD',
    yearZh: '公元 1464–1487 年',
    sortYear: 1470,
    description: 'The "Chicken Cup" utilizes the Doucai (Contending Colors) technique: blue outlines under glaze, filled with enamels over glaze.',
    descriptionZh: '“鸡缸杯”运用了斗彩技法：釉下青花勾勒轮廓，釉上填彩。',
    type: EventType.COURSE,
    tags: ['Ming Dynasty', 'Doucai', 'Chenghua', 'Imperial'],
    tagsZh: ['明代', '斗彩', '成化', '御用'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Chicken_Cup_Chenghua.jpg/800px-Chicken_Cup_Chenghua.jpg'
  },
  {
    id: 'ming-wucai',
    title: 'Ming Dynasty: Wucai Jar',
    titleZh: '明万历：五彩龙纹罐',
    year: '1573–1620 AD',
    yearZh: '公元 1573–1620 年',
    sortYear: 1580,
    description: 'Wucai (Five Color) ware is known for its bold, vibrant palette. Unlike Doucai, it uses blue as a filling color rather than just an outline.',
    descriptionZh: '五彩瓷以其大胆、鲜艳的色彩而闻名。与斗彩不同，它使用蓝色作为填充色，而不仅仅是轮廓。',
    type: EventType.HISTORICAL,
    tags: ['Ming Dynasty', 'Wucai', 'Wanli', 'Polychrome'],
    tagsZh: ['明代', '五彩', '万历', '多色釉'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Wucai_Jar_Wanli_Ming.jpg/800px-Wucai_Jar_Wanli_Ming.jpg'
  },
  {
    id: 'ming-dehua',
    title: 'Late Ming: Dehua Blanc de Chine',
    titleZh: '明代：德化白瓷观音',
    year: 'c. 1600–1644 AD',
    yearZh: '约公元 1600–1644 年',
    sortYear: 1600,
    description: 'Unique for its sugary white body and sculptural form. Dehua porcelain relied entirely on form rather than painted decoration.',
    descriptionZh: '以其如糖般的白色胎体和雕塑造型而独树一帜。德化瓷完全依靠造型而非彩绘装饰。',
    type: EventType.HISTORICAL,
    tags: ['Ming Dynasty', 'Dehua', 'Blanc de Chine', 'Sculpture'],
    tagsZh: ['明代', '德化', '中国白', '雕塑'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Dehua_Guanyin_Ming.jpg/800px-Dehua_Guanyin_Ming.jpg'
  },
  {
    id: 'qing-peachbloom',
    title: 'Qing Dynasty: Peach Bloom',
    titleZh: '清康熙：豇豆红釉',
    year: '1662–1722 AD',
    yearZh: '公元 1662–1722 年',
    sortYear: 1680,
    description: 'A copper-red glaze specially devised for the scholar\'s table. The mottling resembles the skin of a ripening peach or cowpea.',
    descriptionZh: '一种专为文房案头设计的铜红釉。其斑驳的色彩类似成熟桃子的表皮或豇豆。',
    type: EventType.HISTORICAL,
    tags: ['Qing Dynasty', 'Kangxi', 'Peach Bloom', 'Scholar'],
    tagsZh: ['清代', '康熙', '豇豆红', '文房'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Peach-bloom_glazed_water_pot_-_Palace_Museum_Beijing.jpg/800px-Peach-bloom_glazed_water_pot_-_Palace_Museum_Beijing.jpg'
  },
  {
    id: 'qing-famille-rose',
    title: 'Qing Dynasty: Famille Rose',
    titleZh: '清乾隆：粉彩花卉瓶',
    year: 'c. 1735–1796 AD',
    yearZh: '约公元 1735–1796 年',
    sortYear: 1750,
    description: 'This palette introduced opaque whites and pinks, allowing for shading and realistic floral depictions akin to oil painting.',
    descriptionZh: '这种色调引入了不透明的白色和粉红色，使得类似油画的阴影和写实花卉描绘成为可能。',
    type: EventType.COURSE,
    tags: ['Qing Dynasty', 'Famille Rose', 'Enamel', 'Qianlong'],
    tagsZh: ['清代', '粉彩', '珐琅', '乾隆'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Famille_rose_vase_Qianlong.jpg/800px-Famille_rose_vase_Qianlong.jpg'
  },
  {
    id: 'personal-dragon-kiln',
    title: 'Curiosity: The Dragon Kiln',
    titleZh: '设计趣闻：龙窑',
    year: 'Invention c. 200 AD',
    yearZh: '约公元 200 年发明',
    sortYear: 200,
    description: 'Personal Interest Note: I found the engineering of the "Dragon Kiln" (Longyao) fascinating. Built along hillsides to create a natural draft, allowing temperatures to reach 1300°C for the first time.',
    descriptionZh: '个人兴趣笔记：我觉得“龙窑”的工程设计非常迷人。依山而建以形成自然抽力，使温度首次达到 1300°C。',
    type: EventType.PERSONAL,
    tags: ['Engineering', 'Kiln Technology', 'Design Curiosity', 'Personal'],
    tagsZh: ['工程学', '窑炉技术', '设计趣闻', '个人'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Dragon_Kiln_Nanfeng.jpg/800px-Dragon_Kiln_Nanfeng.jpg'
  },
  {
    id: 'personal-grandmother',
    title: 'Grandmother\'s Yixing Teapot',
    titleZh: '家族传承：祖母的紫砂壶',
    year: '1985',
    yearZh: '1985 年',
    sortYear: 1985,
    description: 'A personal artifact. A "zisha" (purple sand) teapot from Yixing. Unglazed, it absorbs tea oils, developing a patina over decades.',
    descriptionZh: '一件个人物品。来自宜兴的“紫砂”茶壶。无釉，吸收茶油，经过数十年形成包浆。',
    type: EventType.PERSONAL,
    tags: ['Family History', 'Yixing', 'Tea Culture', 'Personal'],
    tagsZh: ['家族历史', '宜兴', '茶文化', '个人'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Yixing_Teapot.jpg/800px-Yixing_Teapot.jpg'
  }
];